version: '3.9'
services:
  pii_reverse_proxy_local:
    build:
      context: .
      dockerfile: docker/Local.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: pii_reverse_proxy_local
    profiles:
      - local
    restart: unless-stopped
    ports:
      - 8000:8000
    # For hot reloading
    volumes:
      - ./:/usr/src/pii-reverse-proxy/local
      - ignore://usr/src/pii-reverse-proxy/local/node_modules
volumes:
  ignore:
